### ISSUE TITLE
Path output errors due to chdir

### ISSUE THREAD

**Issue by winged** [p-e-w/maybe#10]
It seems that there's problems with chdir at the moment. If a command chdir()s, path output will not be correct:

    ~ % maybe rm node_modules -rf
      [...]
      delete /home/dv/.travis.yml
      delete /home/dv/readable-stream
      delete /home/dv/node_modules
      delete /home/dv/package.json
      delete /home/dv/readme.md
      delete /home/dv/concat-stream
      delete /home/dv/node_modules

Note that most of the files that seem to be scheduled for deletion in my home dir are actually somewhere in a subdir of node_modules. But since `rm` chdir()s into the subfolders, the output will not correctly contain that subfolder.

**Comment by clball** [comment]
Just to confirm, I was able to reproduce this behavior on Debian Stretch. 

`(stretch)cball@localhost:~$ mkdir test; cd ./test/; mkdir subdir; touch file1; cd ./subdir/; touch file2; cd;

(stretch)cball@localhost:~$ tree test
test
|-- file1
`-- subdir
    `-- file2

1 directory, 2 files

(stretch)cball@localhost:~$ maybe rm -rf test
maybe has prevented rm -rf test from performing 4 file system operations:

  delete /home/cball/file1
  delete /home/cball/file2
  delete /home/cball/subdir
  delete /home/cball/test

Do you want to rerun rm -rf test and permit these operations? [y/N] n`

**Comment by sanketplus** [comment]
can we do something like monitor every `openat` call which causes `chdir()` or `cd` like operation and maintain a `currentPath` variable. 

This `currentPath` which will contain full path can be used as argument for `unlinkat` systemcall which performs the delete operation.

**Comment by p-e-w** [comment]
I am happy to report that with the latest set of commits, this issue is now fully resolved! :tada:

There are two types of relative paths that `maybe` needs to be aware of: The working directory (which can be changed with `chdir`) and the directory pointed to by the file descriptor in the many `*at` syscalls. Fortunately, the `/proc` directory exposes all information required to properly resolve both types of paths within another process, which `maybe` now does.

The downside of this approach is that it isn't portable, so I have decided to drop BSD support and make `maybe` Linux-only. This was not a very hard decision though, as support for Free/OpenBSD was shaky at best already (no tracing of subprocesses) and Linux will be the platform of choice for the vast majority of the target audience anyway.
