### ISSUE TITLE
Support for --help and --version arguments

### ISSUE THREAD

**Issue by Hunter-Github** [p-e-w/maybe#20]
Rationale: to be standard-compliant and discoverable.

**Comment by sanketplus** [comment]
and also `-v` or `--verbose`

I came here to open a new issue for these options and already found this one by @Hunter-Github :sweat_smile: 

Would like to work in it if you think it should be in here @p-e-w :grin:

**Comment by p-e-w** [comment]
Simplicity is a virtue, and parsing command line arguments just to support `--version` is definitely overkill. "Help" can be found by running `maybe` without arguments. `maybe` is "verbose" by default.

If `maybe` ever needs command line arguments that actually do something (I hope not), I will surely add `--version` and `--help` as well. Until then, no.

**Comment by Hunter-Github** [comment]
@p-e-w - do you mind putting `wontfix` tag on the issue, then?

For reference: https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by p-e-w** [comment]
Reopening.

I did not say I won't add `--version` and `--help`. What I said is that supporting these two arguments alone does not justify adding command line parsing. Currently, command line interface standards don't apply to `maybe` because `maybe` does not have a command line interface. If it ever gets one, these two arguments will surely be supported.

**Comment by p-e-w** [comment]
Simple command line parsing has now been added, supporting both `--help` and `--version`.
