### ISSUE TITLE
Feature: more permissive licensing

### ISSUE THREAD

**Issue by dbkaplun** [p-e-w/maybe#45]
Hello,

maybe is amazing! It would be great if maybe switched from GPLv3 to something less [restrictive](https://opensource.google.com/docs/thirdparty/licenses/#restricted). That way it can be included in projects without requiring the project to have a restricted license as well.

Thanks for considering!

**Comment by p-e-w** [comment]
Nope.

I share code with the world for free because I believe that sharing code is beneficial. It is therefore logical for me to choose a license that encourages others to share as well.

This idea was actually widely understood once, before Open Source became yet another tool for Big Business. Your link is quite hilarious, in a sad way – Google does **not** get to define what constitutes a "restrictive" license.

I realize that copyleft is less popular today, mostly thanks to corporations that love to take the work public contributors give freely in good faith, then benefit from it without giving back their extensions to the community. There isn't much I can do about that, but I am more than happy to ignore this trend for my own projects, and choose the license I philosophically believe is best.
